### PR TITLE
Proofreading of entire repo

### PR DESCRIPTION
**Pull request by mdkbmi**
- Renamed, reorganised conda-lock files
- Updated README.md
- Proofread Jupyter notebook

### CODE REVIEW

**Review by davyxuximin — APPROVED** [review]
looks great, ready to submit

**Review by zze1999 — APPROVED** [review]
Really good proofreading! Thanks

**Review by zze1999 — APPROVED** [review]
Looks good for Reference!

**Review by zze1999 — APPROVED** [review]
Looks great for the conda Lock

**Pull request merged**
